### ISSUE TITLE
Please publish version 1.0.3

### ISSUE THREAD

**Issue by IncPlusPlus** [taylorjg/dotnet-versioninfo#3]
Hi there. Thanks for making such a nifty little tool. I'm on an environment that uses .NET 6.0 and I can't run your tool without encountering the following error.
```
You must install or update .NET to run this application.

App: C:\Users\Ryan Cloherty\.nuget\packages\dotnet-versioninfo\1.0.2\tools\netcoreapp2.1\any\dotnet-versioninfo.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '2.1.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  5.0.16 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  5.0.17 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64
```
I had a look at the repo and I think #2 would solve this. Although it's been merged, I don't think it's been published to NuGet yet. Would you mind publishing the latest release when you get the chance? Thanks!

**Comment by taylorjg** [comment]
Hi - sorry for the delay. I was on holiday last week. And my NuGet key had expired. And I didn't even have .NET installed on my current MBP. Anyway, I finally got round to publishing 1.0.3 to NuGet.

**Comment by IncPlusPlus** [comment]
No worries! Hope you had a nice vacation. It works like a charm now. Thanks!
